### PR TITLE
SmolyakExperiment: add nesting support

### LINKED ISSUE #2842: incorrect Fejer nodes for low discretization
### What happened?

fejer nodes/weights seem incorrect for low discretization (nan with clenshaw/n=1, null wieghts with fejer2/n=2), but ok from n>=3

### How to reproduce the issue?

```shell
import openturns as ot
for n in [1, 2, 3, 7]:
    for rule in [ot.FejerAlgorithm.FEJERTYPE1, ot.FejerAlgorithm.FEJERTYPE2, ot.FejerAlgorithm.CLENSHAWCURTIS]:
        algo = ot.FejerAlgorithm([n], rule)
        print(f"n={n} rule={rule}", algo.getNodes().asPoint(), algo.getWeights())

n=1 rule=0 [6.12323e-17] [2]
n=1 rule=1 [6.12323e-17] [0]
n=1 rule=2 [-nan] [inf]
n=2 rule=0 [0.707107,-0.707107] [1,1]
n=2 rule=1 [0.5,-0.5] [0,0]
n=2 rule=2 [1,-1] [1,1]
n=3 rule=0 [0.866025,6.12323e-17,-0.866025] [0.444444,1.11111,0.444444]
n=3 rule=1 [0.707107,6.12323e-17,-0.707107] [0.5,1,0.5]
n=3 rule=2 [1,6.12323e-17,-1] [0.333333,1.33333,0.333333]
n=7 rule=0 [0.974928,0.781831,0.433884,6.12323e-17,-0.433884,-0.781831,-0.974928] [0.0867162,0.287831,0.398242,0.454422,0.398242,0.287831,0.0867162]
n=7 rule=1 [0.92388,0.707107,0.382683,6.12323e-17,-0.382683,-0.707107,-0.92388] [0.167504,0.283333,0.332496,0.433333,0.332496,0.283333,0.167504]
n=7 rule=2 [1,0.866025,0.5,6.12323e-17,-0.5,-0.866025,-1] [0.0285714,0.253968,0.457143,0.520635,0.457143,0.253968,0.0285714]
```
```


### Version

master

### Operating System

all

### Installation media

from source

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by jschueller**
- 1. Add FejerExperiment class to computes nodes&weight like FejerAlgorithm as a DOE
```
bounds = ot.Interval(4.0, 5.0)
discretization = [3]
rule = otexp.FejerExperiment.CLENSHAWCURTIS
experiment = otexp.FejerExperiment(discretization, rule)
```
The FejerAlgorithm class is modified to use FejerExperiment internally but its API is unchanged

- 2. Add WeightedExperiment.setLevels(Indices) level nesting service, used in FejerExperiment to use n=2^L-1 nodes (default=NotYetImplemented for non-nested DOEs)

- 3. In SmolyakExperiment, use setLevels if possible instead of setSize, thus allowing for nested tensorization

### CODE REVIEW

**Comment by mbaudin47** [comment]
Very well done: thank you for this feature. 

- "_Should we drop `FejerAlgorithm` and use `FejerExperiment`+`ExperimentIntegration` ?_" I don't think so. In #2709, I explain why the design of `ExperimentIntegration` could be improved since it does not inherits from `IntegrationAlgorithmImplementation` which can be seen here:

https://github.com/openturns/openturns/blob/master/lib/src/Uncertainty/Algorithm/WeightedExperiments/openturns/ExperimentIntegration.hxx#L34

  Instead, `FejerAlgorithm` currently inherits from `IntegrationAlgorithmImplementation`, as can be seen here:

https://github.com/openturns/openturns/blob/master/lib/src/Base/Algo/openturns/FejerAlgorithm.hxx#L35

  This is why removing `FejerAlgorithm` cannot be currently done, because it removes a feature that is not fullfilled by `ExperimentIntegration`.

- "_Or only move FejerAlgorithm code to FejerExperiment so FejerAlgorithm uses FejerExperiment ?_" This seems correct from my point of view.
- "_thoughts on WeightedExperiment.setLevel ? note that we have a StratifiedExperiment in base, with stratification service setLevels."_ I have to make a full review of the PR before I can have a view on this.

File: lib/src/Uncertainty/Algorithm/WeightedExperiments/WeightedExperimentImplementation.cxx [hunk 1]
```diff
@@ -97,6 +97,12 @@ UnsignedInteger WeightedExperimentImplementation::getSize() const
   return size_;
 }
 
+/* Level accessor */
+void WeightedExperimentImplementation::setLevels(const Indices & /*levels*/)
+{
+  throw NotYetImplementedException(HERE) << getClassName() << " does not support nesting levels";
```
Comment (jschueller) [inline lib/src/Uncertainty/Algorithm/WeightedExperiments/WeightedExperimentImplementation.cxx:103]: = setSize(product(levels))

File: lib/src/Uncertainty/Algorithm/WeightedExperiments/FejerExperiment.cxx [hunk 2]
```diff
@@ -0,0 +1,368 @@
...
+
+/* Nesting level accessor */
+void FejerExperiment::setLevels(const Indices & levels)
+{
+  const UnsignedInteger size = levels.getSize();
+  if (size != discretization_.getSize())
+    throw InvalidArgumentException(HERE) << "FejerExperiment nesting levels must match discretization size, got " << size;
+  Indices discretization(size);
+  for (UnsignedInteger i = 0; i < size; ++ i)
+    discretization[i] = SpecFunc::IPow(2.0, levels[i]) - 1;
```
Comment (jschueller) [inline lib/src/Uncertainty/Algorithm/WeightedExperiments/FejerExperiment.cxx:130]: add a flag to decide whether to interpret the levels as levels or sizes

File: lib/src/Uncertainty/Algorithm/WeightedExperiments/FejerExperiment.cxx [hunk 3]
```diff
@@ -0,0 +1,131 @@
...
+  weightsOut = algorithm_.getWeights();
+  // Adapt the nodes to the bounds of the interval
+  const Point halfDelta((bounds_.getUpperBound() - bounds_.getLowerBound()) * 0.5);
+  return algorithm_.getNodes() * halfDelta + halfDelta + bounds_.getLowerBound();
+}
+
+/* Size accessor */
+void FejerExperiment::setSize(const UnsignedInteger /*size*/)
+{
+  throw NotDefinedException(HERE) << "in FejerExperiment::setSize";
```
[the remark this answers is not in the document]
Comment (mbaudin47) [reply lib/src/Uncertainty/Algorithm/WeightedExperiments/FejerExperiment.cxx:119]: With `setUseNestedLevels(False)`, this is not a limitation anymore: we can use un-nested Fejer experiment.

**Review by mbaudin47 — APPROVED** [review]

**Comment by adutfoy** [comment]
Thanks for this new development.
I suggest some points: 

1. we should precise that the way all the nodes and weights are computed  is documented on the class FejerAlgorithm. 
2. we should add the link to https://en.wikipedia.org/wiki/Clenshaw%E2%80%93Curtis_quadrature which is very usefull (english version).

It is ok for me to merge it in the library.

**Review by adutfoy — CHANGES_REQUESTED** [review]
Thanks for this new development.
I suggest some points: 

1. we should precise that the way all the nodes and weights are computed  is documented on the class FejerAlgorithm. 
2. we should add the link to https://en.wikipedia.org/wiki/Clenshaw%E2%80%93Curtis_quadrature which is very usefull (english version).

It is ok for me to merge it in the library.

**Comment by jschueller** [comment]
agreed, I moved the nodes/weights expression to fejerexperiment and referenced it from fejeralgorithm
