### PR TITLE
Expand logPDF range below LogMinScalar

### LINKED ISSUE #1558: Example estimate_multivariate_normal: FittingTest::BestModelBIC fails to compute the BIC
In the example [Estimate a multivariate distribution](http://openturns.github.io/openturns/master/examples/data_analysis/estimate_multivariate_distribution.html), generated from [estimate_multivariate_distribution.ipynb](https://github.com/openturns/openturns/blob/master/python/doc/examples/data_analysis/estimate_multivariate_distribution.ipynb), cell 8, copulas are built from 2D marginals of a 4D Sample.

The method `BestModelBIC` of the class `FittingTest` is used, but it fails to accurately compute the BIC. Let us run the notebook and paste the following code in a cell at the bottom:

```
print("-2 * LogMinScalar =", -2.0 * ot.SpecFunc.LogMinScalar)
for num, bloc in enumerate(blocs):
    print("###################################################################")
    print("BIC of", estimated_copulas[num], "for the bloc", bloc, ":")
    print(ot.FittingTest_BIC(sample.getMarginal(bloc), estimated_copulas[num]))
```

We get the following output:

```
-2 * LogMinScalar = 1416.7928370645282
###################################################################
BIC of AliMikhailHaqCopula(theta = 0.601685) for the bloc [0, 3] :
1416.7928370646807
###################################################################
BIC of ClaytonCopula(theta = 2.45478) for the bloc [1, 2] :
1416.7928370646807
```

As this code suggests, I think the issue is that we hit a threshold based on `SpecFunc::LogMinScalar`.

Moreover, I believe the only reason `BestModelBIC` still manages to build the copulas is that for both blocs ([0, 3] and [1, 2]), only one of the considered CopulaFactories actually manages to build a copula, so the BIC computation is irrelevant.

### PR DESCRIPTION
**Pull request by josephmure**
At the last CT, we discussed how we could try replacing `SpecFunc::LogMinScalar` by `-SpecFunc::MaxScalar` whenever possible. This PR implements this idea. It supersedes #1555 and supersedes #1532.

It has several advantages:

1. It makes the code more in line with the mathematical intuition (exp(-inf)=0).
2. OT can deal with wider ranges in the log domain.
3. We can probably remove checks like ``if (logPDF==SpecFunc::LogMinScalar) return ...``
4. It might solve @MerlinKeller's bug regarding not being able to perform a `RandomWalkMetropolisHastings`.

Note that `SpecFunc::LogMinScalar` is sometimes replaced by `-SpecFunc::LogMaxScalar`, `-SpecFunc::MaxScalar`, or even `0.0`, which seems strange. This PR fixes several undetected bugs and corrects several `.expout` files. It also closes #1558.

### CODE REVIEW

**Comment by josephmure** [comment]
This PR is ready for review @jschueller @regislebrun @sofianehaddad @mbaudin47 @MerlinKeller

**Review by MerlinKeller — APPROVED** [review]
This pull request has successfully solved the initial problem, which prevented the use of the RandomWalkMetropolisHastings class.

**Comment by mbaudin47** [comment]
There is a failing unit test revealed on mingw:
```
383/528 Test  #873: pyinstallcheck_WeibullMaxFactory_std ...................................***Failed    2.54 sec
--- /home/devel/project/python/test/t_WeibullMaxFactory_std.expout	2020-10-02 14:48:14.812645859 +0000
+++ /home/devel/project/build/python/test/t_WeibullMaxFactory_std.out	2020-10-02 15:08:48.225228823 +0000
@@ -6,4 +6,4 @@
 Default weibull= WeibullMax(beta = 1, alpha = 1, gamma = 0)
 WeibullMax from parameters= WeibullMax(beta = 1, alpha = 2.5, gamma = -1)
 Estimated distribution= class=WeibullMax name=WeibullMax dimension=1 beta=4.93038e-30 alpha=1 gamma=-2.22045e-16
-Estimated distribution= class=WeibullMax name=WeibullMax dimension=1 beta=9.96953e-05 alpha=1 gamma=1
+Estimated distribution= class=WeibullMax name=WeibullMax dimension=1 beta=9.96898e-05 alpha=1 gamma=1
```

**Comment by josephmure** [comment]
@mbaudin47 I don't understand why `WeibullMaxFactory` produces a different result with mingw than with all other compilers. Do you have any idea?

**Comment by mbaudin47** [comment]
Might it be related to the change of the computeLogPDF in lib/src/Uncertainty/Distribution/WeibullMax.cxx ?

**Comment by josephmure** [comment]
Maybe, but it is weird. The problem with mingw started after my last rebase, it worked fine before.

**Comment by mbaudin47** [comment]
The issue for `WeibullMaxFactory_std` can be fixed with
```
std::setprecision(2)
```
See e.g.:

https://github.com/openturns/openturns/blob/073d803c3bc8e6ec5cea9d38b79d00610098aab3/lib/test/t_ANCOVA_std.cxx#L104

**Comment by mbaudin47** [comment]
Here is a summary of the discussions.

Deux stratégies.
Générer des exceptions
Générer des INF et des NAN
Mauvaise stratégie : générer des warning. C’est trop silencieux.

Arguments contre générer des INF
Ce n’est pas un réel.
Cela produit des résultats inutiles.
La performance des librairies est moins bonne.
On ne sait pas comment les dépendances (NLOPT, etc…) vont réagir à nos INF.

Si la valeur de retour est un INF, lève une exception.

Options constructives
Créer une PR alternative avec des exceptions dans le calcul des logPDF dans toutes les distributions.
Remplacer -MaxScalar par Lowest

Si logPDF = -INF, alors PDF = 0.

**Comment by jschueller** [comment]
il n'y a pas besoin d'ouvrir une nouvelle pr, tu peux faire les modifs ici

**Comment by jschueller** [comment]
can you rebase on master ?

**Comment by josephmure** [comment]
OK, I'll do that.

File: lib/src/Base/Func/SpecFunc/openturns/SpecFunc.hxx [hunk 1]
```diff
@@ -104,6 +104,8 @@ public:
   // Maximum positive real number
   static const Scalar MaxScalar;
   static const Scalar LogMaxScalar;
+  // Minimum negative real number;
+  static const Scalar LowestScalar;
```
Comment (jschueller) [inline lib/src/Base/Func/SpecFunc/openturns/SpecFunc.hxx:108]: what's the point of adding it if its not used ?

Comment (josephmure) [reply lib/src/Base/Func/SpecFunc/openturns/SpecFunc.hxx:108]: It's going to be used! I'll change the early commits during rebase in order to use it.

Comment (jschueller) [reply lib/src/Base/Func/SpecFunc/openturns/SpecFunc.hxx:108]: oh, sorry

**Comment by josephmure** [comment]
I hope I haven't lost anything during the rebase. I still have a copy of the old version locally if necessary. If nothing was lost, then this PR is ready to be merged.

**Comment by josephmure** [comment]
I'm sorry @jschueller. My rebase failed, I'm not sure I can handle this. I think I'll restore the previous version, drop the commit that modified a notebook, and add a commit to replace -SpecFunc::MaxScalar with SpecFunc::LowestScalar.

**Comment by josephmure** [comment]
Now, this is interesting: build_mingw still fails because apparently, the build_linux version of `FittingTest::BIC` still produces `inf` two times. You will need to Ctrl+F "inf" in order to see it:

```
520/528 Test #1010: pyinstallcheck_FittingTest_std .........................................***Failed    0.94 sec
--- /home/devel/project/python/test/t_FittingTest_std.expout	2020-10-13 19:56:02.247292677 +0000
+++ /home/devel/project/build/python/test/t_FittingTest_std.out	2020-10-13 20:20:30.727930288 +0000
@@ -2,7 +2,7 @@
 best model Kolmogorov= class=Uniform name=Uniform dimension=1 a=-1.52961 b=2.50771
 best model AIC= class=Uniform name=Uniform dimension=1 a=-1.52961 b=2.50771
 best model AICc= class=Uniform name=Uniform dimension=1 a=-1.52961 b=2.50771
-resultBIC= class=SquareMatrix dimension=16 implementation=class=MatrixImplementation name=Unnamed rows=16 columns=16 values=[-0.506611,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,0.390135,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,26.4376,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,4.94401,3.40566,3.36873,9.04993,7.59532,36.5729,3.45423,15.9133,4.0612,2.44214,2.97694,3.35073,3.39791,7.22934,6.15453,2.7554,1.79769e+308,3.02206,1.79769e+308,4.87206,1.79769e+308,1.79769e+308,1.79769e+308,7.11503,1.79769e+308,1.79769e+308,4.24283,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,2.84271,5.25018,4.44992,10.9583,3.6054,4.34917,3.02071,17.9129,3.54591,2.94694,4.65243,3.81864,4.44384,8.34608,7.99529,3.72076,3.25977,4.78199,4.40705,14.8314,3.72037,4.27123,3.35483,23.6423,3.66558,3.31367,4.49168,3.98667,4.35917,11.3017,7.80417,3.76417,1.57993,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.96017,1.79769e+308,1.79769e+308,1.79553,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,3.59754,26.8191,20.1943,22.0736,15.3766,25.307,25.7348,25.4331,3.16515,24.2971,25.0307,21.3014,23.5995,22.1146,19.0699,15.8091,23.3449,2.98858,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,2.52017,1.79769e+308,2.95261,2.20348,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,2.72506,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,0,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,2.88821,1.79769e+308,8.7561,1.79769e+308,1.79769e+308,1.79769e+308,15.912,1.79769e+308,1.79769e+308,2.01493,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,2.81418,inf,6.44627,6.73739,3.04985,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,3.44656,3.40759,1.79769e+308,6.70608,2.8749,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,3.5535,inf,4.7839,5.19235,3.71538,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,5.56112,4.7975,6.51924,4.0993,4.97127,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,2.11218]
+resultBIC= class=SquareMatrix dimension=16 implementation=class=MatrixImplementation name=Unnamed rows=16 columns=16 values=[-0.506611,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,0.390135,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,26.4376,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,4.94401,3.40566,3.36873,9.04993,7.59532,36.5729,3.45423,15.9133,4.0612,2.44214,2.97694,3.35073,3.39791,7.22934,6.15453,2.7554,1.79769e+308,3.02206,1.79769e+308,4.87206,1.79769e+308,1.79769e+308,1.79769e+308,7.11503,1.79769e+308,1.79769e+308,4.24283,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,2.84271,5.25018,4.44992,10.9583,3.6054,4.34917,3.02071,17.9129,3.54591,2.94694,4.65243,3.81864,4.44384,8.34608,7.99529,3.72076,3.25977,4.78199,4.40705,14.8314,3.72037,4.27123,3.35483,23.6423,3.66558,3.31367,4.49168,3.98667,4.35917,11.3017,7.80417,3.76417,1.57993,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.96017,1.79769e+308,1.79769e+308,1.79553,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,3.59754,26.8191,20.1943,22.0736,15.3766,25.307,25.7348,25.4331,3.16515,24.2971,25.0307,21.3014,23.5995,22.1146,19.0699,15.8091,23.3449,2.98858,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,2.52017,1.79769e+308,2.95261,2.20348,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,2.72506,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,0,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,2.88821,1.79769e+308,8.7561,1.79769e+308,1.79769e+308,1.79769e+308,15.912,1.79769e+308,1.79769e+308,2.01493,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,2.81418,3.59539e+306,6.44627,6.73739,3.04985,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,3.44656,3.40759,1.79769e+308,6.70608,2.8749,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,3.5535,3.59539e+306,4.7839,5.19235,3.71538,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,5.56112,4.7975,6.51924,4.0993,4.97127,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,1.79769e+308,2.11218]
 Kolmogorov test : case with estimated parameters
 Kolmogorov test : case with known parameters
 Kolmogorov test : case with known parameters, set the level
```

File: lib/src/Uncertainty/StatTests/FittingTest.cxx [hunk 2]
```diff
@@ -382,9 +382,9 @@ Scalar FittingTest::BIC(const Sample & sample,
   const Sample logPDF(distribution.computeLogPDF(sample));
   for (UnsignedInteger i = 0; i < size; ++i)
   {
-    if (logPDF(i, 0) == -SpecFunc::MaxScalar) return SpecFunc::MaxScalar;
     logLikelihood += logPDF(i, 0);
   }
+  if (!SpecFunc::IsNormal(logLikelihood)) return SpecFunc::MaxScalar; // catch infinity and NaN
   return (-2.0 * logLikelihood + estimatedParameters * log(1.0 * size)) / size;
```
Comment (regislebrun) [inline lib/src/Uncertainty/StatTests/FittingTest.cxx:388]: The actual fix should be:
```
const Scalar bic = (-2.0 * logLikelihood + estimatedParameters * log(1.0 * size)) / size;
if (!SpecFunc::IsNormal(bic)) return SpecFunc::MaxScalar;
return bic;
```
otherwise you could get an inf by doubling logLikelihood if its value is large enough.

Comment (josephmure) [reply lib/src/Uncertainty/StatTests/FittingTest.cxx:388]: Yes, that is probably what happens under build_linux. Going to fix that.

Comment (josephmure) [inline lib/src/Uncertainty/StatTests/FittingTest.cxx:388]:
```suggestion
const Scalar bic = (-2.0 * logLikelihood + estimatedParameters * log(1.0 * size)) / size;
if (!SpecFunc::IsNormal(bic)) return SpecFunc::MaxScalar; // catch infinity and NaN
return bic;
```

**Comment by josephmure** [comment]
The rebase is finally complete. If all tests pass, I think this can be merged.

**Comment by josephmure** [comment]
Travis has failed, but I do not think it is due to this PR because the failure occurs before compilation even starts.

**Comment by jschueller** [comment]
yes, I made a fix to the image, can you log into circleci and restart the mingw job ?

**Comment by josephmure** [comment]
Mingw failed again. It is because I forgot to change the C++ `t_WeibullMinFactory_std.cxx` and `t_WeibullMaxFactory_std.cxx`. I only changed the Python versions  `t_WeibullMinFactory_std.py` and `t_WeibullMaxFactory_std.py`.

**Comment by josephmure** [comment]
Now that I think of it, I also forgot to update the ChangeLog.

**Comment by josephmure** [comment]
I have corrected the missing `;`, but the command `make tests` still fails on my local install:

```
openturns/lib/test/t_WeibullMinFactory_std.cxx: In function ‘int main(int, char**)’:
openturns/lib/test/t_WeibullMinFactory_std.cxx:62:47: error: ‘class OT::Distribution’ has no member named ‘getBeta’; did you mean ‘getMean’?
     assert_almost_equal(estimatedDistribution.getBeta(), 0.0, 0.0, 1e-4);
                                               ^~~~~~~
                                               getMean
openturns/lib/test/t_WeibullMinFactory_std.cxx:63:47: error: ‘class OT::Distribution’ has no member named ‘getAlpha’; did you mean ‘getCopula’?
     assert_almost_equal(estimatedDistribution.getAlpha(), 1.0, 0.0, 1e-6);
                                               ^~~~~~~~
                                               getCopula
openturns/lib/test/t_WeibullMinFactory_std.cxx:64:47: error: ‘class OT::Distribution’ has no member named ‘getGamma’; did you mean ‘getName’?
     assert_almost_equal(estimatedDistribution.getGamma(), 1.0, 0.0, 1e-6);
                                               ^~~~~~~~
                                               getName
```

I do not understand this, because `estimatedDistribution` was build as `WeibullMin`:
```
    estimatedDistribution = factory.buildAsWeibullMin(sample);
    assert_almost_equal(estimatedDistribution.getBeta(), 0.0, 0.0, 1e-4);
    assert_almost_equal(estimatedDistribution.getAlpha(), 1.0, 0.0, 1e-6);
    assert_almost_equal(estimatedDistribution.getGamma(), 1.0, 0.0, 1e-6);
```

**Comment by jschueller** [comment]
```
const Point ref = {0,1,1};
assert_almost_equal(estimatedDistribution.getParameter(), ref, 0.0, 1e-4);
```

**Comment by josephmure** [comment]
Mingw passed at last!

**Review by jschueller — APPROVED** [review]

**Review by regislebrun — APPROVED** [review]
