### PR TITLE
Fixes doc issues

### LINKED ISSUE #2364: KrigingAlgorithm: examples set bounds before disabling optimization
Several examples of `KrigingAlgorithm` ([here](https://openturns.github.io/openturns/latest/auto_meta_modeling/kriging_metamodel/plot_kriging_hyperparameters_optimization.html) and [there](https://openturns.github.io/openturns/latest/auto_meta_modeling/kriging_metamodel/plot_kriging_multioutput_firesatellite.html#sphx-glr-auto-meta-modeling-kriging-metamodel-plot-kriging-multioutput-firesatellite-py), and perhaps elsewhere) set the optimization bounds of the covariance model parameters with `setOptimizationBounds` but disables their optimization with `setOptimizeParameters(False)`. Is it on purpose? If so, what is the meaning of this?

### PR DESCRIPTION
**Pull request by mbaudin47**
This PR fixes two bugs:
- the first kriging example mentioned by @mdelozzo in #2364
- the bugs mentioned in the API doc of  `KrigingAlgorithm` by @mdelozzo in #2361 
- the bugs mentioned on `Sample` example in #2359

This PR also fixes other doc bugs.
- This PR also fixes bugs in the Bayesian calibration doc:

image

- This PR provides more detailed explanations on the `ParametricFunction` class.
- It provides an improved example to set a column or a row of a `Sample`.
- It removes unnecessary casts (i.e. class conversions) in some examples.

To do this, I used `docfast.py` with the following parameters:
```bash
$ git add . && cd build && make -j8 && make install && cd .. && python3 utils/docfast.py build-sphinxonly response_surface.rst kriging.rst KrigingAlgorithm.rst GeneralLinearModelAlgorithm.rst glm.rst plot_kriging_hyperparameters_optimization.py
```
When I updated the example with `docfast`, I also added the `KrigingAlgorithm` so that I could made the links active (otherwise, they are just in bold face). But the kriging is in the "Response surface" section of the API help page, so I had to add this section.

### CODE REVIEW

**Comment by josephmure** [comment]
> To do this, I used `docfast.py` with the following parameters:
> 
> ```shell
> $ git add . && cd build && make -j8 && make install && cd .. && python3 utils/docfast.py build-sphinxonly response_surface.rst kriging.rst KrigingAlgorithm.rst GeneralLinearModelAlgorithm.rst glm.rst plot_kriging_hyperparameters_optimization.py
> ```

Why does your command line mention `KrigingAlgorithm.rst` and `GeneralLinearModelAlgorithm.rst`? What are these files?

**Comment by mbaudin47** [comment]
> Why does your command line mention `KrigingAlgorithm.rst` and `GeneralLinearModelAlgorithm.rst`? What are these files?

The corresponding help pages are in KrigingAlgorithm_doc.i.in and GeneralLinearModelAlgorithm_doc.i.in. But these files are unknown to Sphinx. So I added these files to make sure that the corresponding help pages are generated. Is that unnecessary?

**Comment by mbaudin47** [comment]
@josephmure , @m-balesdent : Please review this PR and tell me if that seems OK from your point of view.

**Review by m-balesdent — APPROVED** [review]
Thanks for the job !

File: lib/src/Uncertainty/Algorithm/MetaModel/openturns/MetaModelAlgorithm.hxx [hunk 1]
```diff
@@ -90,7 +90,7 @@ public:
   void load(Advocate & adv) override;
 
   /** Recover the distribution */
-  static Distribution BuildDistribution(const Sample & inputSample);
+  static ComposedDistribution BuildDistribution(const Sample & inputSample);
```
Comment (jschueller) [inline lib/src/Uncertainty/Algorithm/MetaModel/openturns/MetaModelAlgorithm.hxx:93]: why is this needed ?

Comment (mbaudin47) [reply lib/src/Uncertainty/Algorithm/MetaModel/openturns/MetaModelAlgorithm.hxx:93]: The `ComposedDistribution` has a pretty-print, after #2282.
But to express it into the examples, the type of the object has to correspond to the class which has a pretty-print feature. After the modification in the current PR, the distribution truly is a `ComposedDistribution`, which produces:

image

Comment (jschueller) [reply lib/src/Uncertainty/Algorithm/MetaModel/openturns/MetaModelAlgorithm.hxx:93]: in that case the pretty-print method must be added to the Distribution interface class, ant that change must be reverted

Comment (mbaudin47) [reply lib/src/Uncertainty/Algorithm/MetaModel/openturns/MetaModelAlgorithm.hxx:93]: I added a pretty-print to the Distribution at d7f311dc969d301baf5869c638d7d26dc80dbf9e. Notice, however, that this cannot be a replacement for this particular code. This is because the information contained in the ComposedDistribution is much more specific than the information in a Distribution: a ComposedDistribution has a list of 1D marginals, while a Distribution has not. The information contained in the attributes of the Distribution are the dimension, the description, the range and the copula boolean. The pretty-print is an itemized list, but not more.

Comment (jschueller) [reply lib/src/Uncertainty/Algorithm/MetaModel/openturns/MetaModelAlgorithm.hxx:93]: no, the pretty-print will be delegated to ComposedDistribution by inheritance and is done in the implementation so that change is not needed

File: python/test/t_Distribution_std.py [hunk 2]
```diff
@@ -117,6 +117,14 @@
     assert len(p) == len(pd), "len p/pd"
     assert len(pc) == 1, "len(pc)"
     assert len(p) == len(pc[0]), "len p/pc"
+
```
Comment (mbaudin47) [inline python/test/t_Distribution_std.py:120]:
```suggestion

```

File: lib/src/Uncertainty/Algorithm/MetaModel/openturns/MetaModelAlgorithm.hxx (hunk 1 above)
Comment (mbaudin47) [reply lib/src/Uncertainty/Algorithm/MetaModel/openturns/MetaModelAlgorithm.hxx:93]: I was not sure to get the point, so I tested several combinations. There are two options:
- Option 1. The `MetaModelAlgorithm.BuildDistribution()` returns a `ComposedDistribution`.
- Option 2. The `MetaModelAlgorithm.BuildDistribution()` returns a `Distribution`.

There are two sub-options:
- Option A. Implement `Distribution.__Distribution_repr_html` in `Distribution.i`.
- Option B. Do not implement `Distribution.__Distribution_repr_html` in `Distribution.i`.

In all cases, I leave the `_repr_html_` implemented for `ComposedDistribution.i`.

I consider the Python script:
```python
import openturns as ot
inputSample = ot.Normal(2).getSample(1000)
distribution = ot.MetaModelAlgorithm.BuildDistribution(inputSample)
print("distribution = ", distribution)
print("type(distribution) = ", type(distribution))
print("distribution (HTML)")
print(distribution._repr_html_())
print("distribution (Markdown)")
print(distribution._repr_markdown_())
```

- Option 1.A. The `MetaModelAlgorithm.BuildDistribution()` returns a `ComposedDistribution` and I implement `Distribution.__Distribution_repr_html` in `Distribution.i`.
	Script output:
```bash
$ python3 metamodel_builddistribution.py 
distribution =  ComposedDistribution(Normal(mu = -0.0268588, sigma = 0.985838), Normal(mu = 0.00246667, sigma = 1.00015), IndependentCopula(dimension = 2))
type(distribution) =  <class 'openturns.model_copula.ComposedDistribution'>
distribution (HTML)
<ul>
  <li>dimension: 2</li>
  <li>copula: IndependentCopula</li>
</ul>

<table>
  <tr>
    <th>Index</th>
    <th>Variable</th>
    <th>Distribution</th>
  </tr>
  <tr>
    <td>0</td>
    <td>X0</td>
    <td>Normal(mu = -0.0268588, sigma = 0.985838)</td>
  </tr>
  <tr>
    <td>1</td>
    <td>X1</td>
    <td>Normal(mu = 0.00246667, sigma = 1.00015)</td>
  </tr>
</table>

distribution (Markdown)
ComposedDistribution
- name=ComposedDistribution
- dimension=2
- description=[X0,X1]
- copula=IndependentCopula(dimension = 2)

| Index | Variable | Distribution                              |
|-------|----------|-------------------------------------------|
|     0 |       X0 | Normal(mu = -0.0268588, sigma = 0.985838) |
|     1 |       X1 | Normal(mu = 0.00246667, sigma = 1.00015)  |
```
Conclusion: this is the expected behavior.

- Option 1.B. The `MetaModelAlgorithm.BuildDistribution()` returns a `ComposedDistribution` and I do not implement `Distribution.__Distribution_repr_html` in `Distribution.i`.
	Script output:
```bash
$ python3 metamodel_builddistribution.py 
distribution =  ComposedDistribution(Normal(mu = -0.0268588, sigma = 0.985838), Normal(mu = 0.00246667, sigma = 1.00015), IndependentCopula(dimension = 2))

type(distribution) =  <class 'openturns.model_copula.ComposedDistribution'>

distribution (HTML)
<ul>
  <li>dimension: 2</li>
  <li>copula: IndependentCopula</li>
</ul>

<table>
  <tr>
    <th>Index</th>
    <th>Variable</th>
    <th>Distribution</th>
  </tr>
  <tr>
    <td>0</td>
    <td>X0</td>
    <td>Normal(mu = -0.0268588, sigma = 0.985838)</td>
  </tr>
  <tr>
    <td>1</td>
    <td>X1</td>
    <td>Normal(mu = 0.00246667, sigma = 1.00015)</td>
  </tr>
</table>

distribution (Markdown)
ComposedDistribution
- name=ComposedDistribution
- dimension=2
- description=[X0,X1]
- copula=IndependentCopula(dimension = 2)

| Index | Variable | Distribution                              |
|-------|----------|-------------------------------------------|
|     0 |       X0 | Normal(mu = -0.0268588, sigma = 0.985838) |
|     1 |       X1 | Normal(mu = 0.00246667, sigma = 1.00015)  |
```
Conclusion: this is the expected behavior, as before. But `Distribution` does not have a pretty-print anymore. This is not a problem, because this pretty-print is not very interesting.

- Option 2.A.The `MetaModelAlgorithm.BuildDistribution()` returns a `Distribution` and I implement `Distribution.__Distribution_repr_html in Distribution.i`
	Script output:
```bash
$ python3 metamodel_builddistribution.py 
distribution =  ComposedDistribution(Normal(mu = -0.0268588, sigma = 0.985838), Normal(mu = 0.00246667, sigma = 1.00015), IndependentCopula(dimension = 2))

type(distribution) =  <class 'openturns.model_copula.Distribution'>

distribution (HTML)
<ul>
  <li>dimension: 2</li>
  <li>description: [X0,X1]</li>
  <li>range: ]-inf (-7.56914), (7.51542) +inf[
]-inf (-7.64933), (7.65426) +inf[</li>
  <li>isCopula: False</li>
</ul>

distribution (Markdown)
ComposedDistribution
- name=ComposedDistribution
- dimension=2
- weight=1
- range=]-inf (-7.56914), (7.51542) +inf[
]-inf (-7.64933), (7.65426) +inf[
- description=[X0,X1]
- isParallel=true
- isCopula=false
```
Conclusion. The Markdown method is delegated from `Distribution` to `ComposedDistribution`. The HTML method from `Distribution.i` takes the lead and hides the method from `ComposedDistribution.i`. 
The HTML output is disappointing in this case, because the ComposedDistribution is not pretty-printed anymore.

- Option 2.B. The `MetaModelAlgorithm.BuildDistribution()` returns a `Distribution` and I do not implement `Distribution.__Distribution_repr_html` in `Distribution.i`
Script output:
```bash
$ python3 metamodel_builddistribution.py 
distribution =  ComposedDistribution(Normal(mu = -0.0268588, sigma = 0.985838), Normal(mu = 0.00246667, sigma = 1.00015), IndependentCopula(dimension = 2))

type(distribution) =  <class 'openturns.model_copula.Distribution'>

distribution (HTML)
<p>ComposedDistribution(Normal(mu = -0.0268588, sigma = 0.985838), Normal(mu = 0.00246667, sigma = 1.00015), IndependentCopula(dimension = 2))</p>

distribution (Markdown)
Traceback (most recent call last):
  File "/home/devel/Documents/metamodel_builddistribution.py", line 9, in <module>
    print(distribution._repr_markdown_())
AttributeError: 'Distribution' object has no attribute '_repr_markdown_'
```
Conclusion. The HTML output is disappointing in this case, because the `ComposedDistribution` is not pretty-printed anymore. There is no Markdown output.

I think that the behavior that you want can be obtained only if the HTML pretty-print is produced right from the C++ which leave some space for the the inheritance to take place. This is not the case in the current implementation, where the HTML is produced from the Python layer for these objects.

Comment (jschueller) [reply lib/src/Uncertainty/Algorithm/MetaModel/openturns/MetaModelAlgorithm.hxx:93]: yes, it should be done in the c++ side, sorry this wasnt clear enough

**Comment by mbaudin47** [comment]
@jschueller : I plan to proceed as follows:
- remove the unwanted change in BuildDistribution and return a Distribution.
- Implement the html pretty print of ComposedDistribution in C++ by moving in from Python to C++in a separate PR.
- That way, the current PR can be merged as there was no other main issue here. 

Is that OK for you?

**Comment by jschueller** [comment]
seems good

**Comment by mbaudin47** [comment]
> seems good

Created a pretty-print of ComposedDistribution at #2447.

File: lib/src/Uncertainty/Algorithm/MetaModel/openturns/MetaModelAlgorithm.hxx (hunk 1 above)
Comment (mbaudin47) [reply lib/src/Uncertainty/Algorithm/MetaModel/openturns/MetaModelAlgorithm.hxx:93]: This part of the PR is now moved to #2447. This is why I resolve this conversation.

Comment (mbaudin47) [reply lib/src/Uncertainty/Algorithm/MetaModel/openturns/MetaModelAlgorithm.hxx:93]: Oups, the code is still in the PR.

**Review by josephmure — CHANGES_REQUESTED** [review]

File: python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_chaos_build_distribution.py [hunk 3]
```diff
@@ -4,9 +4,14 @@
 """
 # %%
 #
-# In this example we show how to use the `BuildDistribution` function to fit a distribution to an input sample.
-# This function is used by the `FunctionalChaosAlgorithm` class when we want to create a polynomial chaos metamodel and we have a design of experiments which have been computed beforehand.
-# In this case, we have to identify the distributions which best fit to the input sample in order to define the input probabilistic model.
+# In this example we show how to use the
+# :class:`~openturns.BuildDistribution` function to fit a distribution to an
```
Comment (mbaudin47) [inline python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_chaos_build_distribution.py:8]:
```suggestion
# :meth:`~openturns.BuildDistribution` function to fit a distribution to an
```

File: python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_functional_chaos.py [hunk 4]
```diff
@@ -34,32 +47,59 @@
...
+# %%
+# Create the PCE
+# ~~~~~~~~~~~~~~
+
 # %%
 # Create a functional chaos model.
-# First, we need to fit a distribution on the input sample. We can do this automatically with the Lilliefors test.
+# The algorithm needs to fit a distribution on the input sample.
+# To do this, the algorithm in :class:`~openturns.FunctionalChaosAlgorithm`
+# uses the :class:`~openturns.FunctionalChaosAlgorithm.BuildDistribution`
```
Comment (mbaudin47) [inline python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_functional_chaos.py:74]:
```suggestion
# uses the :meth:`~openturns.FunctionalChaosAlgorithm.BuildDistribution`
```

**Review by josephmure — APPROVED** [review]

**Comment by jschueller** [comment]
a rebase is needed

**Comment by jschueller** [comment]
hello @mbaudin47, this seems ready but needs a rebase, can we still target 1.22 ?

**Comment by jschueller** [comment]
+1 but needs a rebase

**Comment by mbaudin47** [comment]
@jschueller : I think this it ready.
