### PR TITLE
Fixed Triangular

### LINKED ISSUE #2095: Triangular::computeCharacteristicfunction() produces NaNs
When m==a or m==b, there is a division by 0 in this method:
```
import openturns as ot

d1 = ot.Triangular(-2.0, -2.0, 4.0)
print(d1.computeCharacteristicFunction(1.0))
d2 = ot.Triangular(-2.0, 4.0, 4.0)
print(d2.computeCharacteristicFunction(1.0))
```
produces:
```
(nan+nanj)
(nan+nanj)
```

### PR DESCRIPTION
**Pull request by regislebrun**
It closes #2095.

The characteristic function produced NaNs in degenerate cases where two breakpoints were equal.

### CODE REVIEW

**Review by jschueller — COMMENTED** [review]
could you add the testcase ?

**Review by jschueller — APPROVED** [review]

File: lib/test/t_Trapezoidal_std.cxx [hunk 1]
```diff
@@ -43,140 +43,159 @@ int main(int, char *[])
...
     {
-      fullprint << "Kolmogorov test for the generator, sample size=" << size << " is " << (FittingTest::Kolmogorov(distribution.getSample(size), distribution).getBinaryQualityMeasure() ? "accepted" : "rejected") << std::endl;
-      size *= 10;
+      // Instantiate one distribution object
+      Trapezoidal distribution(coll[nTrapezoidal]);
+      fullprint << "Distribution " << distribution << std::endl;
+      std::cout << "Distribution " << distribution << std::endl;
+
+      // Is this distribution elliptical ?
+      fullprint << "Elliptical = " << (distribution.isElliptical() ? "true" : "false") << std::endl;
```
Comment (josephmure) [inline lib/test/t_Trapezoidal_std.cxx:64]: This sort of check could be made using assertions.

Comment (regislebrun) [reply lib/test/t_Trapezoidal_std.cxx:64]: As discussed during our last technical meeting, you are right, it could be done using assertions, but as there are two to four such tests in each of the 80 tests related to distributions, I don't see the need to cherry-pick some parts of some tests to convert them to assertions, and unfortunately I don't have the time to convert this test to the new format as a whole...

**Review by josephmure — APPROVED** [review]
Never mind my comment about unit tests, it is not critical.

**Review by sofianehaddad — APPROVED** [review]
