### PR TITLE
Some fixes

### LINKED ISSUE #1590: The equation of the Fejer quadrature rule is triplicated
The equation of the 3 quadrature rules: 

http://openturns.github.io/openturns/master/user_manual/_generated/openturns.FejerAlgorithm.html

but the equations are the same in the three cases:

image

### PR DESCRIPTION
**Pull request by sofianehaddad**
Fix #1590 and #1547

### CODE REVIEW

File: lib/src/Base/Geom/openturns/Mesh.hxx [hunk 1]
```diff
@@ -52,7 +52,8 @@ public:
 
   /** Parameters constructor */
   Mesh(const Sample & vertices,
-       const IndicesCollection & simplices);
+       const IndicesCollection & simplices,
+       const Bool checkMeshValidity = ResourceMap::GetAsBool("Mesh-CheckValidity"));
```
Comment (jschueller) [inline lib/src/Base/Geom/openturns/Mesh.hxx:56]: I suggest to leave the attribute out of the ctor and keep separate accessors,
(we have ctors with several bools and its confusing)

File: lib/src/Base/Geom/Mesh.cxx [hunk 2]
```diff
@@ -65,14 +65,17 @@ Mesh::Mesh(const Sample & vertices)
...
+           const IndicesCollection & simplices,
+           const Bool checkMeshValidity)
   : PersistentObject()
   , dimension_(vertices.getDimension())
   , vertices_(0, vertices.getDimension())
   , simplices_(simplices)
 {
   // Use the vertices accessor to initialize the kd-tree
   setVertices(vertices);
+  if (checkMeshValidity)
```
Comment (jschueller) [inline lib/src/Base/Geom/Mesh.cxx:77]: maybe we could enable it by default for small meshes if < Mesh-LargeSize

File: lib/src/Base/Geom/openturns/Mesh.hxx (hunk 1 above)
Comment (sofianehaddad) [reply lib/src/Base/Geom/openturns/Mesh.hxx:56]: ah

File: lib/src/Base/Geom/Mesh.cxx (hunk 2 above)
Comment (sofianehaddad) [reply lib/src/Base/Geom/Mesh.cxx:77]: Indeed. I had this in mind

File: lib/src/Base/Geom/openturns/Mesh.hxx (hunk 1 above)
Comment (sofianehaddad) [reply lib/src/Base/Geom/openturns/Mesh.hxx:56]: what do you suggest? Having a key but without introducing it in ctor?

File: lib/src/Base/Geom/Mesh.cxx (hunk 2 above)
Comment (sofianehaddad) [reply lib/src/Base/Geom/Mesh.cxx:77]: @jschueller something like that?

File: lib/src/Base/Geom/openturns/Mesh.hxx (hunk 1 above)
Comment (jschueller) [reply lib/src/Base/Geom/openturns/Mesh.hxx:56]: yes, an attribute that would have an accessor, or just using the key

File: lib/src/Base/Geom/Mesh.cxx (hunk 2 above)
Comment (jschueller) [reply lib/src/Base/Geom/Mesh.cxx:77]: yes

File: lib/src/Base/Geom/openturns/Mesh.hxx (hunk 1 above)
Comment (josephmure) [reply lib/src/Base/Geom/openturns/Mesh.hxx:56]: Couldn't we do things this way:

- Always use ``ResourceMap::GetAsBool("Mesh-CheckValidity"))`` (so we don't provide the option to change the behavior in the ctor, which is @jschueller's concern).
- Set the default "Mesh-CheckValidity" to `True`.
- If a user thinks mesh checking takes too long, that user can simply set the ResourceMap key  "Mesh-CheckValidity" to `False`. Then it becomes the user's responsibility to call `isValid` whenever appropriate.

**Comment by regislebrun** [comment]
The main problem is what we intend to check in the validity test. In its current form it is relatively fast, but if we want to add more checks such as "do some simplices overlap?" it will become much more costly. With this in mind, IMO the test should be triggered explicitly by the user. There are different places where the meshes are correct *by construction*, eg in LeveSetMesher or IntervalMesher, and we would have to change the value of the ResourceMap before and after the creation of the mesh in order to avoid this costly test. Another problem is with the setters: do we have to check the mesh after each vertices/simplicies modifications? Sometime a sequence of modifications starts from a valid mesh to end with a valid mesh, but the intermediate meshes are not valid (eg a vertex by vertex modification).

File: lib/src/Base/Geom/openturns/Mesh.hxx (hunk 1 above)
Comment (sofianehaddad) [reply lib/src/Base/Geom/openturns/Mesh.hxx:56]: Finally I think I will keep the parameter in ctor.
Now we do the check if asked only once and store this into an internal attribute. Reason is that several methods require explicitly the check (`draw` for example).

File: lib/src/Base/Geom/Mesh.cxx (hunk 2 above)
Comment (sofianehaddad) [reply lib/src/Base/Geom/Mesh.cxx:80]: Finally I dropped the use of several RM keys for that purpose and rely only on the specific `checkMeshValidity ` one

File: lib/src/Base/Geom/openturns/Mesh.hxx (hunk 1 above)
Comment (regislebrun) [reply lib/src/Base/Geom/openturns/Mesh.hxx:56]: Ok for me

**Review by regislebrun — APPROVED** [review]

**Comment by jschueller** [comment]
+1, but you have to drop the changes on estimate_integral_Fejer.ipynb until Kieran's work is merged

**Review by josephmure — CHANGES_REQUESTED** [review]
I agree with your solution @sofianehaddad  I have 2 alternative suggestions for `Mesh.doc.i.in`: one simply fixes a typo, and the other changes the formulation, so you can pick the one you like best.

**Comment by sofianehaddad** [comment]
> +1, but you have to hold on the changes on estimate_integral_Fejer.ipynb until Kieran's work is merged

ok.

**Review by josephmure — APPROVED** [review]
+1, great job!

File: python/src/Sample.i [hunk 3]
```diff
@@ -786,6 +786,26 @@ Sample(PyObject * pyObj)
   return new OT::Sample( OT::convert< OT::_PySequence_, OT::Sample>(pyObj) );  
 }
 
+static Sample BuildFromSequence(PyObject * pyObj, const OT::UnsignedInteger size, const OT::UnsignedInteger dimension)
+{
```
Comment (jschueller) [inline python/src/Sample.i:790]: -1
when d=1 (like I suppose this will be in most cases) simply writes `ot.Sample([[x] for x in L])` !
even when d>1 this will be `ot.Sample([L[i:i+d] for i in range(0,len(L),d)])` which is not uber difficult
so imho no need for this function when the solution is built-in the language
worst case a simple example would be enough

Comment (sofianehaddad) [reply python/src/Sample.i]: I move this (for discussion) into a new PR in order to not freeze this one
