### PR TITLE
Improved and fixed [Linear|Quadratic]LeastSquares

### LINKED ISSUE #3068: QuadraticLeastSquares.run() is not stable
### What is the idea?

The **QuadraticLeastSquares.run()** method is not implemented using a stable method. 

The current implementation:

https://github.com/openturns/openturns/blob/71b761449dbb77e9d5ba7f47e09bfca95f4dc997/lib/src/Base/MetaModel/QuadraticLeastSquares.cxx#L89

does not center the input, but it should.

### Why is this needed?

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by regislebrun**
Now the data are centered before to compute the parameters using ordinary least-squares. It fixes #3068. 
A factor 0.5 was used for the off-diagonal terms of the quadratic part. It should not. Fixed.

### CODE REVIEW

File: lib/src/Base/Func/QuadraticEvaluation.cxx [hunk 1]
```diff
@@ -1,7 +1,7 @@
 //                                               -*- C++ -*-
 /**
  *  @brief Class for a quadratic function implementation
- *        of the form y = constant + <linear, x-c> + <<quadratic, x-c>, x-c>
+ *        of the form y = constant + <linear, x-c> + 0.5 * <<quadratic, x-c>, x-c>
```
Comment (sofianehaddad) [inline lib/src/Base/Func/QuadraticEvaluation.cxx:4]: hmm it seems you drop the `0.5` factor, isn't it?

Comment (regislebrun) [reply lib/src/Base/Func/QuadraticEvaluation.cxx:4]: @sofianehaddad No, if you expand the quadratic term you get 
$$\frac{1}{2}\sum_{i=1}^d\sum_{j=1}^d (x_i-c_i)(x_j-c_j)=\frac{1}{2}\sum_{i=1}^d(x_i-c_i)+\frac{1}{2}\sum_{i\neq j}(x_i-c_i)(x_jc_j)=\frac{1}{2}\sum_{i=1}^d(x_i-c_i)+\sum_{i<j}(x_i-c_i)(x_jc_j)$$ and there is no more 0.5 factor in front of the double sum, which was the problem I fixed in the PR.

File: python/src/QuadraticFunction_doc.i [hunk 2]
```diff
@@ -18,16 +18,15 @@ This class implements a quadratic function :math:`f` defined as:
...
 .. math::
 
-    f : & \Rset^d \rightarrow \Rset^p  \\
-        & \vect{X} \mapsto \Tr{\mat{A}} ( \vect{X} - \vect{b} ) + \vect{c} + \frac{1}{2} \vect{X}^T.
-        \underline{\underline{\underline{M}}}. \vect{X}
-
+    f : & \Rset^\inputDim \rightarrow \Rset^\outputDim  \\
+        & \vect{c} + \vect{X} \mapsto \Tr{\mat{A}} ( \vect{X} - \vect{b} ) + \frac{1}{2} \Tr{( \vect{X} - \vect{b} )}.
+        \underline{\underline{\underline{M}}}.( \vect{X} - \vect{b} )
 where:
```
Comment (jschueller) [inline python/src/QuadraticFunction_doc.i:25]: keep the line skip before where

File: python/src/QuadraticLeastSquares_doc.i [hunk 3]
```diff
@@ -6,71 +6,38 @@ Parameters
...
-:math:`(a_j  \, , \, j=0, \cdots,P-1)` is a set of unknown coefficients and the
-family :math:`(\psi_j,j=0,\cdots, P-1)` gathers the constant monomial :math:`1`,
-the monomials of degree one :math:`x_i`, the cross-terms :math:`x_i x_j` as
-well as the monomials of degree two :math:`x_i^2`. Using the vector notation
-:math:`\vect{a} \, = \, (a_{0} , \cdots , a_{P-1} )^{\textsf{T}}` and
-:math:`\vect{\psi}(\vect{x}) \, = \, (\psi_0(\vect{x}), \cdots, \psi_{P-1}(\vect{x}) )^{\textsf{T}}`,
-this rewrites:
-
-.. math::
+ .. math::
```
Comment (jschueller) [inline python/src/QuadraticLeastSquares_doc.i]:
```suggestion
.. math::
```

File: python/src/QuadraticFunction_doc.i (hunk 2 above)
Comment (regislebrun) [reply python/src/QuadraticFunction_doc.i:25]: fixed

File: python/src/QuadraticLeastSquares_doc.i (hunk 3 above)
Comment (regislebrun) [reply python/src/QuadraticLeastSquares_doc.i]: fixed

File: python/src/QuadraticLeastSquares_doc.i [hunk 4]
```diff
@@ -6,71 +6,38 @@ Parameters
...
-:math:`h(\vect{x})` over its whole domain of definition. A common choice to
-this end is global polynomial approximation.
+A least squares meta model provides an approximation of the model which is valid over its whole domain of definition.
 
-We consider here a global approximation of the model response using  a
-quadratic function:
+This class estimates the meta model :math:`\metaModel: \Rset^\inputDim \rightarrow \Rset^\outputDim` defined by: 
 
 .. math::
+    :label: QuadraticLeastSquaresMMOpenTURNSAPI
```
Comment (jschueller) [inline python/src/QuadraticLeastSquares_doc.i:18]: I think you have to skip a line after :label:

File: python/src/QuadraticLeastSquares_doc.i [hunk 5]
```diff
@@ -6,71 +6,38 @@ Parameters
...
-:math:`\vect{\cX} =(x^{(1)},\cdots,x^{(N)})`, i.e. a set of realizations of
-input parameters is required, as well as the corresponding model evaluations
-:math:`\vect{\cY} =(y^{(1)},\cdots,y^{(N)})`.
-
-The following minimization problem has to be solved:
+from an experimental design :math:`\cX` of size :math:`\sampleSize`, that is, a set of observations of
+the input vector defined by:
 
 .. math::
+    :label: inputData
```
Comment (jschueller) [inline python/src/QuadraticLeastSquares_doc.i]: here too

File: python/src/QuadraticLeastSquares_doc.i [hunk 6]
```diff
@@ -6,71 +6,38 @@ Parameters
...
-                                \left(
-                                y^{(i)} \; - \;
-                                \Tr{\vect{a}} \vect{\psi}(\vect{x}^{(i)})
-                                \right)^2
-
-The solution is given by:
+and the corresponding output vectors:
 
 .. math::
+    :label: outputData
```
Comment (jschueller) [inline python/src/QuadraticLeastSquares_doc.i]: and here

File: python/src/LinearLeastSquares_doc.i [hunk 7]
```diff
@@ -6,69 +6,37 @@ Parameters
...
-least squares regression approach. In this context, an experimental design
-:math:`\vect{\cX} =(x^{(1)},\cdots,x^{(N)})`, i.e. a set of realizations of
-input parameters is required, as well as the corresponding model evaluations
-:math:`\vect{\cY} =(y^{(1)},\cdots,y^{(N)})`.
-
-The following minimization problem has to be solved:
+and the corresponding output vectors:
 
 .. math::
+    :label: outputData
```
Comment (jschueller) [inline python/src/LinearLeastSquares_doc.i]: here too

File: python/doc/theory/meta_modeling/least_squares.rst [hunk 8]
```diff
@@ -0,0 +1,166 @@
...
+Least squares meta models
+-------------------------
+
+A least squares meta model provides an approximation of the model :math:`\model: \Rset^\inputDim \rightarrow \Rset^\outputDim` which is valid over its whole domain of definition.
+
+Let :math:`\model: \Rset^\inputDim \rightarrow \Rset^\outputDim`. The objective is to create a meta model
+:math:`\metaModel` defined by:
+
+  .. math::
+      :label: LSMetaModel
```
Comment (jschueller) [inline python/doc/theory/meta_modeling/least_squares.rst]: here

File: python/doc/theory/meta_modeling/least_squares.rst [hunk 9]
```diff
@@ -0,0 +1,166 @@
...
+where, for :math:`0 \leq j \leq N`, :math:`\vect{a}_j \in \Rset^\outputDim` and
+:math:`\psi_j: \Rset^\inputDim \rightarrow \Rset` with :math:`\psi_0: \vect{x} \rightarrow 1`.
+
+The functional basis :math:`(\psi_j)_{0 \leq j \leq N}` is specified and the objective it to determine the
+coefficients :math:`(\vect{a}_j)_{0 \leq j \leq N}`.
+
+Let :math:`\mat{A} \in \cM_{N+1, \outputDim}` and :math:`\vect{\Psi(\vect{x})} \in \Rset^{N+1}` be defined by:
+
+  .. math::
+    :label: defAPsi
```
Comment (jschueller) [inline python/doc/theory/meta_modeling/least_squares.rst:25]: here

File: python/doc/theory/meta_modeling/least_squares.rst [hunk 10]
```diff
@@ -0,0 +1,166 @@
...
+    \mat{A} & = \Tr{(\vect{a}_0 | \dots | \vect{a}_N)}\\
+    \vect{\Psi(\vect{x})} & = \Tr{(\Psi_0(\vect{x}), \dots, \Psi_N(\vect{x})}
+
+Then the meta model :eq:`LSMetaModel` can be written as:
+
+  .. math::
+      :label: LSMetaModelMat
```
Comment (jschueller) [inline python/doc/theory/meta_modeling/least_squares.rst]: and here

File: python/doc/theory/meta_modeling/least_squares.rst [hunk 11]
```diff
@@ -0,0 +1,166 @@
...
+.. math::
+
+    \cY = \left\{ \vect{y}^{(1)}, \dots, \vect{y}^{(\sampleSize)} \right\}.
+
+where :math:`\vect{y}^{(k)} = \model{ \vect{x}^{(k)}}`.
+
+We define the objective function :math:`\cJ` by:
+
+.. math::
+    :label: objFunc
```
Comment (jschueller) [inline python/doc/theory/meta_modeling/least_squares.rst:55]: here

File: python/doc/theory/meta_modeling/least_squares.rst [hunk 12]
```diff
@@ -0,0 +1,166 @@
...
+    \cJ(\mat{A}) = \sum_{i=1}^\sampleSize \left \| \vect{y}^{(i)} - \Tr{\mat{A}} \vect{\Psi(\vect{x}^{(i))}
+    \right \|_{L^2}^2
+
+Then we search :math:`\widehat{\mat{A}}` that minimizes the objective function :eq:`objFunc`:
+
+.. math::
+    :label: defA
```
Comment (jschueller) [inline python/doc/theory/meta_modeling/least_squares.rst:63]: and here

File: python/doc/theory/meta_modeling/least_squares.rst [hunk 13]
```diff
@@ -0,0 +1,166 @@
...
+be defined by:
+
+.. math::
+    \mat{Psi} & = (\psi_j(\vect{x}^{(i)}))_{i,j}\\
+    \mat{Y}    & = \Tr{(\vect{y}^{(1)} | \dots | \vect{y}^{(\sampleSize)}}
+
+Then :math:`\widehat{\mat{A}}` is solution of the linear system:
+
+.. math::
+:label: pbLeastSquares
```
Comment (jschueller) [inline python/doc/theory/meta_modeling/least_squares.rst]: and here, check the indent too

File: python/doc/theory/meta_modeling/least_squares.rst [hunk 14]
```diff
@@ -0,0 +1,166 @@
...
+by:
+
+  .. math::
+  :label defCenter
+     \vect{b} = \dfrac{1}{\sampleSize} \sum_{i=1}^\sampleSize \vect{x}^{(i)}
+
+The resulting meta model can be written as:
+
+  .. math::
+    :label: LinearLeastSquaresMMOpenTURNS
```
Comment (jschueller) [inline python/doc/theory/meta_modeling/least_squares.rst:113]: and here

File: python/doc/theory/meta_modeling/least_squares.rst [hunk 15]
```diff
@@ -0,0 +1,166 @@
...
+     \metaModel(\vect{x})  =  \vect{c} + \Tr{\mat{L}}(\vect{x} - \vect{b}}
+
+where the matrix :math:`\mat{L} \in \cM_{\inputDim, \outputDim}` is
+equal to the matrix :math:`\mat{A}` defined in :eq:`defAPsi` except its first line.
+More precisely, we have:
+
+  .. math::
+    :label: LinearMatrixOpenTURNS
```
Comment (jschueller) [inline python/doc/theory/meta_modeling/least_squares.rst:122]: and here

File: python/doc/theory/meta_modeling/least_squares.rst [hunk 16]
```diff
@@ -0,0 +1,166 @@
...
+
+  .. math::
+      :label: QuadLSMetaModel
+      \metaModel(\vect{x})  = \sum_{j=0}^\inputDim \vect{a}_j \Psi_j(\vect{x}) + \sum_{1 \leq i < j \leq \inputDim
+      }^\inputDim \vect{a}_{ij}\Psi_{ij}(\vect{x})
+
+The resulting meta model can be written as:
+
+  .. math::
+    :label: QuadraticLeastSquaresMMOpenTURNS
```
Comment (jschueller) [inline python/doc/theory/meta_modeling/least_squares.rst:149]: these too

File: python/src/QuadraticLeastSquares_doc.i [hunk 17]
```diff
@@ -135,32 +142,47 @@ dataOut : 2-d sequence of float
...
 
 Returns
 -------
 result : :class:`~openturns.MetaModelResult`
-    An approximation of the function :math:`h` by Quadratic Least Squares."
+    The class that contains all the results on the meta model. 
+    
+Notes
+-----
+To get the meta model :math:`\metaModel` defined in :eq:`QuadraticLeastSquaresMMOpenTURNSAPI` as a :class:`~openturns.Function`, use the :meth:``~openturns.MetaModelResult.getMetaModel` method.
```
Comment (jschueller) [inline python/src/QuadraticLeastSquares_doc.i]: double `

File: python/src/LinearLeastSquares_doc.i [hunk 18]
```diff
@@ -6,69 +6,40 @@ Parameters
...
-and the family :math:`(\psi_j,j=0,\cdots, n_X)` gathers the constant monomial
-:math:`1` and the monomials of degree one :math:`x_i`. Using the vector
-notation :math:`\vect{a} \, = \, (a_{0} , \cdots , a_{n_X} )^{\textsf{T}}` and
-:math:`\vect{\psi}(\vect{x}) \, = \, (\psi_0(\vect{x}), \cdots, \psi_{n_X}(\vect{x}) )^{\textsf{T}}`,
-this rewrites:
+from an experimental design :math:`\cX` of size :math:`\sampleSize`, that is, a set of observations of
+the input vector defined by:
 
 .. math::
+    :label: inputData
```
Comment (jschueller) [inline python/src/LinearLeastSquares_doc.i]: inputData/outputData lables are duplicated in QuadraticLeastSqaures: they must be unique

File: python/src/LinearLeastSquares_doc.i [hunk 19]
```diff
@@ -133,22 +142,32 @@ dataOut : 2-d sequence of float
...
 
 Returns
 -------
 result : :class:`~openturns.MetaModelResult`
-    An approximation of the function :math:`h` by Linear Least Squares."
+    The class that contains all the results on the meta model. 
+    
+Notes
+-----
+To get the meta model :math:`\metaModel` defined in :eq:`LinearLeastSquaresMMOpenTURNSAPI` as a :class:`~openturns.Function`, use the :meth:``~openturns.MetaModelResult.getMetaModel` method.
```
Comment (jschueller) [inline python/src/LinearLeastSquares_doc.i]: double `` here too

also line too long

File: python/doc/theory/meta_modeling/least_squares.rst [hunk 20]
```diff
@@ -0,0 +1,178 @@
...
+    :label defCenter
+
+    \vect{b} = \dfrac{1}{\sampleSize} \sum_{i=1}^\sampleSize \vect{x}^{(i)}
+
+The resulting meta model can be written as:
+
+.. math::
+    :label: LinearLeastSquaresMMOpenTURNS
+
+    \metaModel(\vect{x})  =  \vect{c} + \Tr{\mat{L}}(\vect{x} - \vect{b}}
```
Comment (jschueller) [inline python/doc/theory/meta_modeling/least_squares.rst]: parenthesis instead bracket

Comment (regislebrun) [reply python/doc/theory/meta_modeling/least_squares.rst]: sphinx=hell=nightmare=$£!%!

File: python/src/LinearLeastSquares_doc.i [hunk 21]
```diff
@@ -6,69 +6,40 @@ Parameters
...
-We consider here a global approximation of the model response using  a linear
-function:
+This class estimates the meta model :math:`\metaModel: \Rset^\inputDim \rightarrow \Rset^\outputDim` defined by: 
 
 .. math::
+    :label: LinearLeastSquaresMMOpenTURNSAPI
 
-    \vect{y} \, \approx \, \widehat{h}(\vect{x}) \,
-                      = \, \sum_{j=0}^{n_X} \; a_j \; \psi_j(\vect{x})
+    \metaModel(\vect{x})  =  \vect{c} + \Tr{\mat{L}}(\vect{x} - \vect{b}}
```
Comment (jschueller) [inline python/src/LinearLeastSquares_doc.i]: here too

File: python/doc/theory/meta_modeling/least_squares.rst (hunk 20 above)
Comment (jschueller) [reply python/doc/theory/meta_modeling/least_squares.rst]: I advise to write equations incrementally, not all at once
or, check locally in ottemplatepython then copy-paste into the real doc

File: python/doc/examples/functional_modeling/vectorial_functions/plot_quadratic_function.py [hunk 22]
```diff
@@ -7,8 +7,8 @@
 # In this example we are going to create a quadratic function of the form
 #
 # .. math::
-#    f : \underline{X} \mapsto \underline{\underline{A}} ( \underline{X} - \underline{b} ) + \underline{c}
-#    + \frac{1}{2} \underline{X}^T \times \underline{\underline{\underline{M}}} \times \underline{X}
+#    f : \vect{x} \mapsto \mat{A}} ( \vect{X} - \vect{b} ) + \vect{c}
```
Comment (jschueller) [inline python/doc/examples/functional_modeling/vectorial_functions/plot_quadratic_function.py]: `\mat{A}}` : extra bracket

Comment (regislebrun) [reply python/doc/examples/functional_modeling/vectorial_functions/plot_quadratic_function.py]: It's like walking barefoot on broken glass and burning coals.

Thanks for the help!

File: python/doc/theory/meta_modeling/least_squares.rst [hunk 23]
```diff
@@ -0,0 +1,178 @@
...
+.. math::
+
+    \psi_0 & : \vect{x} \rightarrow 1\\
+    \psi_j & : \vect{x} \rightarrow x_j - b_j, \quad 1 \leq j \leq \inputDim
+
+with :math:`\vect{b} \in \Rset^\inputDim` is the empirical mean vector of the experimental design, defined
+by:
+
+.. math::
+    :label defCenter
```
Comment (jschueller) [inline python/doc/theory/meta_modeling/least_squares.rst]: `:label:`

File: python/doc/theory/meta_modeling/least_squares.rst [hunk 24]
```diff
@@ -0,0 +1,178 @@
+.. _least_squares:
```
Comment (jschueller) [inline python/doc/theory/meta_modeling/least_squares.rst:1]: this conflicts with another label in theory/numerical_methods/least_squares.rst

File: python/src/LinearLeastSquares_doc.i (hunk 21 above)
Comment (regislebrun) [reply python/src/LinearLeastSquares_doc.i]: fixed

File: python/doc/theory/meta_modeling/least_squares.rst (hunk 23 above)
Comment (regislebrun) [reply python/doc/theory/meta_modeling/least_squares.rst]: fixed

File: python/doc/theory/meta_modeling/least_squares.rst (hunk 24 above)
Comment (regislebrun) [reply python/doc/theory/meta_modeling/least_squares.rst:1]: fixed. I renamed this file and updated the labels accordingly.

**Comment by jschueller** [comment]
ok for you @sofianehaddad ?

**Comment by sofianehaddad** [comment]
Yes go
