### PR TITLE
Fix FittingTest class

### LINKED ISSUE #1130: Inconsistency in FittingTest
We fixed #1057 and now `FittingTest::BestModelBIC` returns both the *estimated distribution *(for `DistributionFactory` as argument) and *BIC* value

However `FittingTest::BIC` returns **only** the *BIC* value even if the argument is a `DistributionFactory` 
This inconsistency should be fixed

### PR DESCRIPTION
**Pull request by sofianehaddad**
Now we return the estimated distribution when the `factory` is provided as input argument.

It fixes #1130

### CODE REVIEW

**Comment by sofianehaddad** [comment]
> This should be listed in the API changes, otherwise ok

Indeed

**Comment by regislebrun** [comment]
+1

File: lib/src/Uncertainty/StatTests/openturns/FittingTest.hxx [hunk 1]
```diff
@@ -79,8 +79,9 @@ public:
                     const UnsignedInteger estimatedParameters = 0);
 
   /** Bayesian Information Criterion computation */
-  static Scalar BIC(const Sample & sample,
-                    const DistributionFactory & factory);
+  static Distribution BIC(const Sample & sample,
+                          const DistributionFactory & factory,
+                          Scalar & bestBICOut);
```
Comment (jschueller) [inline lib/src/Uncertainty/StatTests/openturns/FittingTest.hxx]: Wait, if you swap the arguments you have the distribution first:
```
estimated_distribution, bic = FittingTest.BIC(sample, factory)
```
whereas kolmogorov returns the test result first:
```
test_result, estimated_distribution = FittingTest.Kolmogorov(sample, factory)
```

Comment (sofianehaddad) [reply lib/src/Uncertainty/StatTests/openturns/FittingTest.hxx]: indeed.

Comment (sofianehaddad) [reply lib/src/Uncertainty/StatTests/openturns/FittingTest.hxx]: BIc is a `scalar` wheras `test_result` is of type `TestResult`
I suggest to get `estimated_distribution,  bic` and `estimated_distribution,   test_result` 

ok for you?

Comment (jschueller) [reply lib/src/Uncertainty/StatTests/openturns/FittingTest.hxx]: Yes, my remark was just the order of the distribution

Comment (jschueller) [reply lib/src/Uncertainty/StatTests/openturns/FittingTest.hxx]: You can chose the order of the most used convention.
